### ISSUE TITLE
Hello, I am very interested in how to run this source code. Is there a release version of the EXE program?

### ISSUE THREAD

**Issue by 653310641** [Xplatforms/J2534_OIP_Wrapper#19]

**Comment by Xplatforms** [comment]
Hi, not yet. work in progress. But you can already compile j2534 wrapped dll and App exe to play around... Just use Qt 6.* fr App(exe) and Qt 5.* to compile 32-bit j2534 Dll, for j2534 5.05 64-bit you can use the same Qt 6 version as for App compilation.

**Comment by 653310641** [comment]
> Hi, not yet. work in progress. But you can already compile j2534 wrapped dll and App exe to play around... Just use Qt 6.* fr App(exe) and Qt 5.* to compile 32-bit j2534 Dll, for j2534 5.05 64-bit you can use the same Qt 6 version as for App compilation.

Hi, I am not familiar with Qt 6. Can you send me the EXE and DLL files directly?
